package road_fighter.networking;

public enum Comando {
	HACER_NADA, CREAR_SALA, OBTENER_SALAS, AL_LOBBY, ELIMINAR_SALA, UNIRSE_SALA, COMENZAR_PARTIDA, ACELERAR,
	DESACELERAR, DESPLAZAR_IZQUIERDA, DESPLAZAR_DERECHA, COLISION;
}
